moviesproject/moviesapp/urls.py
from django.urls import path
from . import views
app_name='movieapp'
urlpatterns = [

    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.details,name='details'),
    path('add/',views.addMovie,name='addMovie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')
]

moviesproject/moviesproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("moviesapp.urls"))
]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,
                        document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,
                         document_root=settings.MEDIA_ROOT)

moviesproject/moviesapp/models.py
from django.db import models

# Create your models here.
class Movies(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField(null=True)
    year=models.IntegerField()
    img=models.ImageField(upload_to='image')

    def __str__(self):
        return self.name

moviesproject/moviesapp/forms.py
from django import forms
from .models import Movies


class MoviesForm(forms.ModelForm):
    class Meta:
        model=Movies
        fields=['name','desc','year','img']

moviesproject/moviesapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import Movies
from .forms import MoviesForm

# Create your views here.

def index(request):
    movie = Movies.objects.all()
    context = {
        'movie_list': movie
    }
    return render(request, 'index.html', context)


def details(request, movie_id):
    movie = Movies.objects.get(id=movie_id)
    return render(request, "details.html", {'movie': movie})


def addMovie(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        desc = request.POST.get('desc')
        year = request.POST.get('year')
        img = request.FILES['img']
        movie = Movies(name=name, desc=desc, year=year, img=img)
        movie.save()
        return redirect('/')
    return render(request, 'add.html')

def update(request,id):
    movie=Movies.objects.get(id=id)
    form=MoviesForm(request.POST or None,request.FILES,instance=movie)
    if form .is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie })
def delete(request,id):
    if request.method=='POST':
        movie=Movies.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')


moviesproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
        <input type="text" name="name"  placeholder="Enter name of the movie"><br>
        <input type="text" name="description"  placeholder="Enter description of the movie"><br>
        <input type="text" name="year"  placeholder="Enter year of the movie"><br>
        <input type="file" name="img"><br>
        <input type="submit"><br>
</form>
<a href="/" class="btn btn-dark">Home</a>
{% endblock %}

moviesproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> movieapplication</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
      Online Movies Platform
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

moviesproject/templates/delete.html
<form method="POST">
    {% csrf_token %}
    Are you want to delete this movie?<br>
    <input type="submit" placeholder="Submit">


</form>

moviesproject/templates/details.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movie.img.url}}" width="300" height="300">
            <h1>{{movie.name}}</h1>
        </div>
<div class="col-md-6">

    <h2>Description</h2><h6>{{movie.desc}}</h6>
    <h2>year</h2><h6>{{movie.year}}</h6><br>

    <a class="btn btn-warning" href="{%  url 'movieapp:update' movie.id %}">update</a>
    <a class="btn btn-danger" href="{%  url 'movieapp:delete' movie.id %}">delete</a>

</div>


    </div>
</div>
{% endblock %}

moviesproject/templates/edit.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

moviesproject/templates/index.html
{% extends 'base.html' %}
<h1>Movies List </h1>
{% block body %}



<div class="container">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-lg-3">
            <div class="card" style="margin-bottom:30px">
  <img class="card-img-top" src="{{i.img.url}}" alt="" height="200px">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <a href="{% url  'movieapp:details' i.id %}" class="btn btn-danger">View details</a>
  </div>

</div>

        </div>

        {% endfor %}

    </div>
    <a href="add/" class="btn btn-success">add movie</a>
    </div>
</div>




{% endblock %}